version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: devops/app-prod.dockerfile
    environment:
      # we must override the host. here host is name of compose service, docker resolves it
      DATABASE_URI: 'host=psql port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable'
    depends_on:
      - psql
    ports:
      - "8081:8080"
    networks:
      - authmcrsrv_network

  psql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - authmcrsrv_network

volumes:
  psql_data:
    name: authmcrsrv_psql_data

networks:
  authmcrsrv_network: