version: '3.7'

services:
  authmcrsrv:
    build:
      context: .
      dockerfile: devops/authmcrsrv.dockerfile
    depends_on:
      - psql

  psql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: 'authmcrsrv_db'
      POSTGRES_USER: 'authmcrsrv_user'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "54320:5432"
