version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: devops/app.dockerfile
    depends_on:
      - psql
    volumes:
      - ./go.mod:/var/www/go.mod
      - ./.env:/var/www/.env
      - ./migrations:/var/www/migrations
      - ./cmd/server/server_linux_amd64:/var/www/server_linux_amd64
    ports:
      - "8080:8080"

  psql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: 'authmcrsrv_db'
      POSTGRES_USER: 'authmcrsrv_user'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  psql_data:
    name: authmcrsrv_psql_data