version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: devops/app.dockerfile
    depends_on:
      - psql
    volumes:
      - app_data:/var/www

  psql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: 'authmcrsrv_db'
      POSTGRES_USER: 'authmcrsrv_user'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data

volumes:
  app_data:
    name: authmcrsrv_app_data
  psql_data:
    name: authmcrsrv_psql_data