version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: devops/app.dockerfile
    depends_on:
      - psql
    volumes:
      - ./go.mod:/app/go.mod
      - ./.env:/app/.env
      - ./migrations:/app/migrations
    ports:
      - "8080:8080"
    networks:
      - authmcrsrv_network

  psql:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: 'authmcrsrv_db'
      POSTGRES_USER: 'authmcrsrv_user'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "54320:5432"
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - authmcrsrv_network

volumes:
  psql_data:
    name: authmcrsrv_psql_data

networks:
  authmcrsrv_network: