/*
 * internal/infrastructure/protobuf/contracts.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type ProtobufUpdateUserRequest struct {
	Bio string `json:"bio,omitempty"`

	CategoriesIds []string `json:"categories_ids,omitempty"`
}
