/*
 * internal/infrastructure/protobuf/contracts.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import "time"

type ProtobufOrderEntity struct {
	ID          int64     `json:"ID,omitempty"`
	AuthorID    int64     `json:"AuthorID,omitempty"`
	BuyerID     int64     `json:"BuyerID,omitempty"`
	Title       string    `json:"Title,omitempty"`
	Description string    `json:"Description,omitempty"`
	Price       int64     `json:"Price,omitempty"`
	CreatedAt   time.Time `json:"CreatedAt,omitempty"`
	UpdatedAt   time.Time `json:"UpdatedAt,omitempty"`
	ClosedAt    time.Time `json:"ClosedAt,omitempty"`
	DeletedAt   time.Time `json:"DeletedAt,omitempty"`
}
