name: Test
on: [pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.0

      - name: Calculate coverage
        run: |
          ./scripts/get_test_coverage_percentages.sh > artefacts/coverage.txt
          COVERAGE=$(cat artefacts/coverage.txt)
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV

      - name: Generate Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 978ef5ee70cf8245eff5c7957ef6e9ee
          filename: test.json
          label: coverage
          message: ${{ env.COVERAGE }}
          valColorRange: ${{ env.COVERAGE }}
          minColorRange: 40
          maxColorRange: 90
