name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      # Your original steps
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install
        run: npm install
      - name: Test and Coverage
        run: make coverage_ctrf

      # Add this
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main